name: Deploy with Jekyll main and dev

on:
  push:
    branches: [main, dev]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main
        uses: actions/checkout@v4
        with:
          ref: main
          path: main

      - name: Checkout dev
        uses: actions/checkout@v4
        with:
          ref: dev
          path: dev

      - name: Setup Pages
        uses: actions/configure-pages@v5

      # === main ===
      - name: Build main with Jekyll
        uses: actions/jekyll-build-pages@v1
        with:
          source: ./main
          destination: ./output

      # === dev ===
      - name: Build dev with Jekyll
        uses: actions/jekyll-build-pages@v1
        with:
          source: ./dev
          destination: ./output/dev

      - name: Finalize
        run: |
          mv output _site

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v4